### PR TITLE
Fix exhaustiveness checking to account for case guards

### LINKED ISSUE #4466: Failure to pattern match at runtime
## Description

```purescript
data Sound = Moo | Quack | Bark

type Animal = { sound :: Sound }

animalFunc ∷ Array Animal -> Unit
animalFunc animals
  | Just { sound } <- animals # Array.find \{ sound: Moo } -> true = unit
  | otherwise = unit
```
The above example compiles successfully, but throws an unhandled exception at runtime if you call the function with one of the `Sound` enum values not pattern matched in `animalFunc` (such as `Quack` or `Bark`).

## To Reproduce

Build and run the above example.

## Expected behavior

The build should fail because not all enum values are explicitly handled. 

## Additional context

Similar examples we found that also compiled successfully:

```purescript
animalFunc ∷ Animal -> Boolean
animalFunc animal
  | (\{ sound: Moo } -> true) $ animal = true
  | otherwise = false
```
```purescript
animalFunc ∷ Animal -> Boolean
animalFunc animal
  | (let { sound: Moo } = animal in true) = true
  | otherwise = false
````

## PureScript version

0.15.7

### PR DESCRIPTION
**Pull request by purefunctor**
**Description of the change**

Closes #4466. This makes it so that `checkExhaustiveExpr` is defined in terms of `everywhereOnValuesM` rather than a custom recursion routine.

---

**Checklist:**

- [x] Added a file to CHANGELOG.d for this PR (see CHANGELOG.d/README.md)
- [x] Added myself to CONTRIBUTORS.md (if this is my first contribution)
- [x] Linked any existing issues or proposals that this pull request should close
- [ ] Updated or added relevant documentation
- [x] Added a test for the contribution (if applicable)

### CODE REVIEW

File: src/Language/PureScript/Linter/Exhaustive.hs [hunk 1]
```diff
@@ -291,42 +291,19 @@ checkExhaustive ss env mn numArgs cas expr = makeResult . first ordNub $ foldl'
...
-
-  onCaseAlternative :: SourceSpan -> CaseAlternative -> m CaseAlternative
-  onCaseAlternative ss (CaseAlternative x [MkUnguarded e]) = CaseAlternative x . mkUnguardedExpr <$> onExpr ss e
-  onCaseAlternative ss (CaseAlternative x es) = CaseAlternative x <$> mapM (onGuardedExpr ss) es
-
-  onGuardedExpr :: SourceSpan -> GuardedExpr -> m GuardedExpr
-  onGuardedExpr ss (GuardedExpr guard rhs) = GuardedExpr guard <$> onExpr ss rhs
-
-  mkUnguardedExpr = pure . MkUnguarded
+  (_, onExpr', _) = everywhereOnValuesM pure onExpr pure
```
Comment (purefunctor) [inline src/Language/PureScript/Linter/Exhaustive.hs:302]: I wonder if it makes sense to have the source span as a context here w/ `everywhereWithContextOnValues`.

**Review by garyb — APPROVED** [review]

File: src/Language/PureScript/Linter/Exhaustive.hs (hunk 1 above)
Comment (rhendric) [reply src/Language/PureScript/Linter/Exhaustive.hs:302]: Or maybe we should drop `initSS` entirely and use the bounding span of the spans used in `cas`. That'd require some new utility code similar to `declSourceAnn`/`declSourceSpan` but I think it'd probably be useful to have around for more than this.

Either way, minor refinement, I wouldn't block on it.

File: tests/purs/failing/4466.purs [hunk 2]
```diff
@@ -0,0 +1,17 @@
+-- @shouldFailWith NoInstanceFound
+module Main where
+
+import Prelude
+
+import Data.Array as Array
+import Data.Maybe (Maybe(..))
+import Partial.Unsafe (unsafePartial)
```
Comment (rhendric) [inline tests/purs/failing/4466.purs:8]: Unused.

File: src/Language/PureScript/Linter/Exhaustive.hs [hunk 3]
```diff
@@ -291,42 +291,19 @@ checkExhaustive ss env mn numArgs cas expr = makeResult . first ordNub $ foldl'
...
   :: forall m
-   . MonadWriter MultipleErrors m
+   . (MonadError MultipleErrors m, MonadWriter MultipleErrors m)
    => SourceSpan
    -> Environment
    -> ModuleName
    -> Expr
    -> m Expr
-checkExhaustiveExpr initSS env mn = onExpr initSS
+checkExhaustiveExpr initSS env mn = onExpr'
```
Comment (rhendric) [inline src/Language/PureScript/Linter/Exhaustive.hs:300]: If we keep `initSS` as it is currently, it should probably be renamed to just `ss`.

**Review by rhendric — CHANGES_REQUESTED** [review]

File: src/Language/PureScript/Linter/Exhaustive.hs [hunk 4]
```diff
@@ -14,22 +14,22 @@ import Protolude (ordNub)
...
 import Data.Text qualified as T
 
 import Language.PureScript.AST.Binders (Binder(..))
-import Language.PureScript.AST.Declarations (CaseAlternative(..), Declaration(..), ErrorMessageHint(..), Expr(..), Guard(..), GuardedExpr(..), pattern MkUnguarded, pattern ValueDecl, isTrueExpr)
+import Language.PureScript.AST.Declarations (CaseAlternative(..), Expr(..), Guard(..), GuardedExpr(..), pattern MkUnguarded, isTrueExpr)
 import Language.PureScript.AST.Literals (Literal(..))
 import Language.PureScript.Crash (internalError)
 import Language.PureScript.Environment (DataDeclType, Environment(..), TypeKind(..))
-import Language.PureScript.Errors (MultipleErrors, pattern NullSourceAnn, SimpleErrorMessage(..), SourceSpan, addHint, errorMessage')
+import Language.PureScript.Errors (MultipleErrors, pattern NullSourceAnn, SimpleErrorMessage(..), SourceSpan, errorMessage', everywhereOnValuesM)
```
[the remark this answers is not in the document]
Comment (purefunctor) [reply src/Language/PureScript/Linter/Exhaustive.hs:30]: Oops, code actions 😄

**Review by rhendric — APPROVED** [review]
