### PR TITLE
fixes #2172: allow escape sequences in JS FFI exported using strings

### LINKED ISSUE #2172: Bug in FFI identifier validation
For the following FFI module:

    exports['replace\''] = function(x) { ... };

I get the following error:

> The identifier `replace\'` is not valid in PureScript.
> Note that exported identifiers in FFI modules must be valid PureScript identifiers.

To fix it, I have to write:

    exports["replace'"] = function(x) { ... };

This is silly.

### PR DESCRIPTION
**Pull request by michaelficarra**
Fixes #2172.

### CODE REVIEW

**Comment by michaelficarra** [comment]
Some of the Travis builds passed and some failed 😕. Not sure what to do.

**Comment by hdgarrood** [comment]
Is examples/passing/2172.js being included in the source distribution? If not, the purescript.cabal file may need amending. It looks like the OSX builds may be failing because of a corrupted cache or a bug in the build script anyway though, which I can investigate this weekend if nobody else gets there first.

**Comment by michaelficarra** [comment]
Thanks, @hdgarrood. I've amended the `purescript.cabal` file to include `examples/passing/*.js`.

File: src/Language/PureScript/Bundle.hs [hunk 1]
```diff
@@ -186,11 +187,32 @@ withDeps (Module modulePath es) = Module modulePath (map expandDeps es)
...
 -- String literals include the quote chars
 fromStringLiteral :: JSExpression -> Maybe String
-fromStringLiteral (JSStringLiteral _ str) = Just $ trimStringQuotes str
+fromStringLiteral (JSStringLiteral _ str) = Just $ strValue str
 fromStringLiteral _ = Nothing
 
-trimStringQuotes :: String -> String
-trimStringQuotes str = reverse $ drop 1 $ reverse $ drop 1 $ str
+strValue :: String -> String
+strValue str = go $ reverse $ drop 1 $ reverse $ drop 1 str
```
Comment (paf31) [inline src/Language/PureScript/Bundle.hs]: So `language-javascript` gives the raw escaped string, straight out of the JS source?

File: src/Language/PureScript/Bundle.hs [hunk 2]
```diff
@@ -186,11 +187,32 @@ withDeps (Module modulePath es) = Module modulePath (map expandDeps es)
 
 -- String literals include the quote chars
 fromStringLiteral :: JSExpression -> Maybe String
-fromStringLiteral (JSStringLiteral _ str) = Just $ trimStringQuotes str
+fromStringLiteral (JSStringLiteral _ str) = Just $ strValue str
 fromStringLiteral _ = Nothing
 
-trimStringQuotes :: String -> String
-trimStringQuotes str = reverse $ drop 1 $ reverse $ drop 1 $ str
+strValue :: String -> String
```
Comment (paf31) [inline src/Language/PureScript/Bundle.hs]: This isn't blocking, but we should try to avoid the two `reverse` applications here, by looking for the final character in `go`.

**Comment by paf31** [comment]
Thanks for this! I've cleared out the build cache in Travis, so we'll see what happens.

File: src/Language/PureScript/Bundle.hs (hunk 1 above)
Comment (michaelficarra) [inline src/Language/PureScript/Bundle.hs]: Yeah, unfortunately.

File: src/Language/PureScript/Bundle.hs (hunk 2 above)
Comment (michaelficarra) [inline src/Language/PureScript/Bundle.hs]: Will do.

**Comment by paf31** [comment]
CI passes with the cache cleared out.

Is this ready to merge then? If so, I'll merge this and 0.9 into master, and then we can release 0.9.1 tomorrow.

**Comment by michaelficarra** [comment]
@paf31 Should be good to go once CI finishes.

**Comment by paf31** [comment]
Failing due to `-Werror` and 

```
In an equation for `go': Patterns not matched: []
```

**Comment by michaelficarra** [comment]
@paf31 Fixed (even though it's unreachable 😓).

**Comment by paf31** [comment]
Thanks!
