### PR TITLE
TCO Fixes

### LINKED ISSUE #2689: var can capture mutable value in TCO loop
psc version: 0.10.7

In the `sumTCObug` function below, `n` is reset to zero in TCO code, even though `f'` binds `n`. The result is that `f'` adds `a` to zero. If `f'` is inlined, i.e. `go (\a -> n + a) 0` on the last line, then TCO is not triggered and the correct result is returned. If `f'` is `(+) n` then the correct result is also returned, since no JavaScript function closing over `n` is generated.

    sumTCObug = go id
        where 
      go f n = 
        if n == 0 then
          f
        else
          let
            f' a = n + a
          in
            go f' 0

    sumTCObug 7 3 -- Returns 3 instead of 10.

In the generated JavaScript code below, lines 13 and 16 make up the problematic combination.

    var sumTCObug = (function () {
        var go = function (__copy_f) {
            return function (__copy_n) {
                var f = __copy_f;
                var n = __copy_n;
                tco: while (true) {
                    var $0 = n === 0;
                    if ($0) {
                        return f;
                    };
                    if (!$0) {
                        var f$prime = function (a) {
                            return n + a | 0;
                        };
                        f = f$prime;
                        n = 0;
                        continue tco;
                    };
                    throw new Error("Failed pattern match at Main line 27, column 5 - line 35, column 1: " + [ $0.constructor.name ]);
                };
            };
        };
        return go(Control_Category.id(Control_Category.categoryFn));
    })();

### PR DESCRIPTION
**Pull request by paf31**
This moves values which might capture variables into a separate function which introduces new bindings for the same names. This makes TCO more generally applicable and fixes #2689 and #2714.

Here is the generated code for the example: https://gist.github.com/paf31/57cd7d3cce310cf2e9dd347cd7caccf5

@michaelficarra Would you mind having a look at the generated code as well, please?

### CODE REVIEW

File: src/Language/PureScript/CodeGen/JS/Optimizer/TCO.hs [hunk 1]
```diff
@@ -43,65 +48,76 @@ tco = everywhereOnJS convert where
...
-                  ++ [ JSContinue ss tcoLabel ]
+    loopify (JSReturn ss ret)
+      | isSelfCall ident ret =
+        let
+          allArgumentValues = concat $ collectArgs [] ret
+        in
+          JSBlock ss $
+            zipWith (\val arg ->
+              JSAssignment ss (JSVar ss (tcoVar arg)) val) allArgumentValues allArgs
+              ++ [ JSReturn ss (JSVar ss "undefined") ]
```
Comment (michaelficarra) [inline src/Language/PureScript/CodeGen/JS/Optimizer/TCO.hs]: You should be able to just delete this line.

Comment (paf31) [inline src/Language/PureScript/CodeGen/JS/Optimizer/TCO.hs]: Well since we're replacing an existing `return`, and that block might fall through otherwise, I think we need to leave this in.

**Comment by paf31** [comment]
Thanks for the review!

File: src/Language/PureScript/CodeGen/JS/Optimizer/TCO.hs [hunk 2]
```diff
@@ -43,65 +48,76 @@ tco = everywhereOnJS convert where
...
+      JSBlock rootSS $
         map (\arg -> JSVariableIntroduction rootSS arg (Just (JSVar rootSS (copyVar arg)))) allArgs ++
-        [ JSLabel rootSS tcoLabel $ JSWhile rootSS (JSBooleanLiteral rootSS True) (JSBlock rootSS [ everywhereOnJS loopify js ]) ]
+        [ JSVariableIntroduction rootSS tcoDone (Just (JSBooleanLiteral rootSS False))
+        , JSVariableIntroduction rootSS tcoResult Nothing
+        ] ++
+        map (\arg ->
+          JSVariableIntroduction rootSS (tcoVar arg) Nothing) allArgs ++
+        [ JSFunction rootSS (Just tcoLoop) allArgs (JSBlock rootSS [loopify js])
+        , JSLabel rootSS tcoLabel $
```
Comment (michaelficarra) [inline src/Language/PureScript/CodeGen/JS/Optimizer/TCO.hs]: This label is no longer used.

File: src/Language/PureScript/CodeGen/JS/Optimizer/TCO.hs (hunk 1 above)
Comment (michaelficarra) [inline src/Language/PureScript/CodeGen/JS/Optimizer/TCO.hs]: Does the PureScript compiler ever generate code with early returns like that? I figured this would only ever occur at the natural end of execution anyway. But it doesn't hurt I guess. I mostly just didn't like the reference to `undefined`. `return void 0` or `return` or simply leaving it out would all be preferable.

File: src/Language/PureScript/CodeGen/JS/Optimizer/TCO.hs (hunk 2 above)
Comment (paf31) [inline src/Language/PureScript/CodeGen/JS/Optimizer/TCO.hs]: Ah good point, thanks.

File: src/Language/PureScript/CodeGen/JS/Optimizer/TCO.hs (hunk 1 above)
Comment (paf31) [inline src/Language/PureScript/CodeGen/JS/Optimizer/TCO.hs]: Yes, I think I'll change this to a plain `return`. I don't think we generate early returns during code gen, but other optimizations can generate them.

**Comment by paf31** [comment]
@michaelficarra How's this?

Once this is merged, I think I'll rename the `JS.*` modules to `CoreImp` and move `Optimizer.*` out of `CodeGen.JS`.

**Comment by michaelficarra** [comment]
Not really sure why we needed to add `JSReturnNoResult`. Couldn't we have just made `JSReturn` take a `Maybe JS`?

**Comment by paf31** [comment]
It was just much faster to do it this way, and I figured since we'll be doing refactoring to extract the core imperative AST soon anyway, that we can combine them at that point.

**Comment by paf31** [comment]
Thanks!
