### PR TITLE
Fix spurious import suggestions when re-exporting

### LINKED ISSUE #1862: psc suggesting to import everything from Prelude
When compiling the following file in the linked commit from the purescript-email-validate package, psc suggests that I import everything from Prelude, even though I am not using everything from Prelude.

https://github.com/cdepillabout/purescript-email-validate/blob/4b47b9c05fbaa9596d4139a7c375eff6c89a0b3c/src/Text/Email/Validate.purs#L11

Here is the output of `pulp build`:

```
$ pulp build
* Building project in /home/ec2-user/git/purescript-email-validate
psc: No files found using pattern: src/**/*.js
Warning found:
in module Text.Email.Validate
at /home/ec2-user/git/purescript-email-validate/src/Text/Email/Validate.purs line 11, column 1 - line 13, column 1

  Module Prelude has unspecified imports, consider using the explicit form:

    import Prelude (class Applicative, class Apply, class Bind, class BooleanAlgebra, class Bounded, class BoundedOrd, class Category, class DivisionRing, class Eq, class Functor, class ModuloSemiring, class Monad, class Num, class Ord, class Ring, class Semigroup, class Semigroupoid, class Semiring, class Show, Unit, Ordering(EQ, GT, LT), add, ap, append, apply, asTypeOf, bind, bottom, compare, compose, conj, const, disj, div, eq, flip, id, liftA1, liftM1, map, mod, mul, negate, not, one, otherwise, pure, return, show, sub, top, unit, unsafeCompare, void, zero, (#), ($), (&&), (*), (+), (++), (-), (/), (/=), (<), (<#>), (<$>), (<*>), (<<<), (<=), (<>), (==), (>), (>=), (>>=), (>>>), (||))



See https://github.com/purescript/purescript/wiki/Error-Code-ImplicitImport for more information,
or to contribute content related to this warning.

* Build successful.
```

It should only be suggesting something like this:

```purescript
import Prelude ((==), (<<<), ($), show, map)
```

### PR DESCRIPTION
**Pull request by garyb**
Resolves #1862.

The linked issue arises whenever there were unspecified imports in a module that exported _any_ module. Doing that would result in all members being suggested for the members with unspecified imports.

### CODE REVIEW

File: src/Language/PureScript/Linter/Imports.hs [hunk 1]
```diff
@@ -155,17 +155,22 @@ lintImports (Module _ _ mn mdecls mexports) env usedImps = do
     go (q, name) = M.alter (Just . maybe [name] (name :)) q
 
   extractByQual
-    :: (Eq a)
+    :: (Show a, Eq a)
```
Comment (paf31) [inline src/Language/PureScript/Linter/Imports.hs]: `Show`?

**Comment by paf31** [comment]
👍

File: src/Language/PureScript/Linter/Imports.hs (hunk 1 above)
Comment (garyb) [inline src/Language/PureScript/Linter/Imports.hs]: Oops, debug leftover :)
