### PR TITLE
Fix errors when generating Haddocks

### LINKED ISSUE #4072: PureScript compile error when -haddock
## Description

PureScript code is not correct for haddock.

## To Reproduce

when settting,

~~~yaml
ghc-options:
  "$everything": -haddock
~~~

run it,

~~~console
yarn global add purescript
~~~

~~~console
  purescript    > /tmp/node-purescript-t4g6V9/src/Language/PureScript/TypeChecker/Roles.hs:209:11: error:
  purescript    >     parse error on input ‘-- * If the role is nominal, mark all free variables in the’
  purescript    >     |
  purescript    > 209 |           -- * If the role is nominal, mark all free variables in the
  purescript    >     |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
~~~

## Expected behavior

install is succeed.

## Additional context

The reason for making document generation the default is that HLS does not work well if this is not enabled.

I will open PR.

## PureScript version

0.14.1

### PR DESCRIPTION
**Pull request by ncaq**
[PureScript compile error when -haddock · Issue #4072 · purescript/purescript](https://github.com/purescript/purescript/issues/4072)

**Description of the change**

added: haddock check in CI.
fixed: haddock error.

Fixes #4072.

---

**Checklist:**

- [x] Added the change to the changelog's "Unreleased" section with a reference to this PR (e.g. "- Made a change (#0000)")
- [x] Linked any existing issues or proposals that this pull request should close
- [x] Updated or added relevant documentation
- [ ] Added a test for the contribution (if applicable)

### CODE REVIEW

File: src/Language/PureScript/TypeChecker/Kinds.hs [hunk 1]
```diff
@@ -587,11 +587,10 @@ type DataDeclarationArgs =
   , [DataConstructorDeclaration]
   )
 
+-- | (The infered type signatures of data constructors, The inferred kind of the declaration)
 type DataDeclarationResult =
   ( [(DataConstructorDeclaration, SourceType)]
-  -- ^ The infered type signatures of data constructors
```
Comment (hdgarrood) [inline src/Language/PureScript/TypeChecker/Kinds.hs:592]: If this is causing an error, I'd rather just remove the `^`. If these are not kept inline to the fields the describe I think they are much more likely to go out of date.

File: ci/build.sh [hunk 2]
```diff
@@ -19,7 +19,7 @@ set -ex
 # for compilation or for tests in our package.yaml file (these sorts of issues
 # don't test to get noticed until after releasing otherwise).
 
-STACK="stack --no-terminal --jobs=2"
+STACK="stack --no-terminal --haddock --jobs=2"
```
Comment (hdgarrood) [inline ci/build.sh:22]: We have gone back and forth on this a couple of times, so I think we should add a comment explaining why it is necessary so that it doesn't get removed again later to speed CI up. For example:

> We test with `--haddock` because haddock generation can fail if there is invalid doc-comment syntax, and these failures are very easy to miss otherwise.

File: src/Language/PureScript/TypeChecker/Roles.hs [hunk 3]
```diff
@@ -206,13 +206,15 @@ inferDataDeclarationRoles moduleName (tyName, tyArgs, ctors) roleEnv =
...
           -- arguments. For each (role, argument) pair:
           --
-          -- * If the role is nominal, mark all free variables in the
-          --   argument as nominal also, since they cannot be coerced if the
-          --   argument's nominality is to be preserved.
-          -- * If the role is representational, recurse on the argument, since
-          --   its use of our parameters is important.
-          -- * If the role is phantom, terminate, since the argument's use of
-          --   our parameters is unimportant.
+          -- If the role is nominal,
```
Comment (hdgarrood) [inline src/Language/PureScript/TypeChecker/Roles.hs:209]: Can you tidy up the line wrapping here please?

**Review by hdgarrood — COMMENTED** [review]
Looks good so far! Please add yourself to CONTRIBUTORS.md too.

File: src/Language/PureScript/TypeChecker/Kinds.hs (hunk 1 above)
Comment (ncaq) [reply src/Language/PureScript/TypeChecker/Kinds.hs:592]: I change to inline.

File: ci/build.sh (hunk 2 above)
Comment (ncaq) [reply ci/build.sh:24]: I added comment.

File: src/Language/PureScript/TypeChecker/Roles.hs (hunk 3 above)
Comment (ncaq) [reply src/Language/PureScript/TypeChecker/Roles.hs]: I delete too much newline.

**Comment by ncaq** [comment]
I write CONTRIBUTORS.md and code review findings.
Please check.

File: src/Language/PureScript/TypeChecker/Kinds.hs [hunk 4]
```diff
@@ -588,10 +588,8 @@ type DataDeclarationArgs =
   )
 
 type DataDeclarationResult =
-  ( [(DataConstructorDeclaration, SourceType)]
-  -- ^ The infered type signatures of data constructors
-  , SourceType
-  -- ^ The inferred kind of the declaration
+  ( [(DataConstructorDeclaration, SourceType)] -- The infered type signatures of data constructors
```
Comment (hdgarrood) [inline src/Language/PureScript/TypeChecker/Kinds.hs:591]: I'd prefer like this like it was before, so that the lines aren't too long.
```suggestion
  ( [(DataConstructorDeclaration, SourceType)]
    -- The infered type signatures of data constructors
```

File: src/Language/PureScript/TypeChecker/Kinds.hs [hunk 5]
```diff
@@ -588,10 +588,8 @@ type DataDeclarationArgs =
...
+  , SourceType -- The inferred kind of the declaration
```
Comment (hdgarrood) [inline src/Language/PureScript/TypeChecker/Kinds.hs:592]:
```suggestion
  , SourceType
    -- The inferred kind of the declaration
```

File: src/Language/PureScript/TypeChecker/Kinds.hs [hunk 6]
```diff
@@ -639,10 +637,8 @@ type TypeDeclarationArgs =
   )
 
 type TypeDeclarationResult =
-  ( SourceType
-  -- ^ The elaborated rhs of the declaration
-  , SourceType
-  -- ^ The inferred kind of the declaration
+  ( SourceType -- The elaborated rhs of the declaration
```
Comment (hdgarrood) [inline src/Language/PureScript/TypeChecker/Kinds.hs:640]:
```suggestion
  ( SourceType
  -- The elaborated rhs of the declaration
```

File: src/Language/PureScript/TypeChecker/Kinds.hs [hunk 7]
```diff
@@ -639,10 +637,8 @@ type TypeDeclarationArgs =
...
+  , SourceType -- The inferred kind of the declaration
```
Comment (hdgarrood) [inline src/Language/PureScript/TypeChecker/Kinds.hs:641]:
```suggestion
  , SourceType
  -- The inferred kind of the declaration
```

**Comment by rhendric** [comment]
Should the remedy here actually be keeping the bullets and arrows, and just indenting them more? AIUI the Haddock lexer rules specifically match the character sequence `-- ^` etc., so using `--  ^` for example (note the extra space) should be fine and would better preserve the original clarity of the comments, in my opinion.

**Comment by hdgarrood** [comment]
That approach sounds reasonable to me

**Review by JordanMartinez — APPROVED** [review]
CI builds and it seems like this is ready to merge.

**Comment by JordanMartinez** [comment]
Can we get another approval here so we can merge this?

**Comment by hdgarrood** [comment]
I haven't approved this because the formatting/alignment is still a bit off. I want to leave everything as-is as far as possible when merging this change. In particular alignment is a big no-no for me: it means that diffs become much more noisy and you're forced to change lines that aren't relevant to a particular change to keep code lined up, which means that eg `git blame` is much less likely to give you the information you want immediately.

**Comment by hdgarrood** [comment]
Also, @rhendric's suggestion hasn't been implemented. Although, in retrospect I'm tempted to not use that trick, because it seems a bit "clever" - I think it's likely that people will think we did actually mean to use `-- ^` and try to "correct" it.

**Comment by hdgarrood** [comment]
Also, the line lengths are wonky in TypeChecker/Roles, I think we should restore the previous wrapping too.

**Comment by JordanMartinez** [comment]
@ncaq Just curious. Do you anticipate getting back to this sometime soon? If not, would you mind if I built on top of this, making the changes requested above?

**Comment by ncaq** [comment]
@JordanMartinez 
I'm not sure what the code standard is there, so it seems faster to fix it there.
Therefore, I think I'll leave it to you.

**Comment by JordanMartinez** [comment]
I believe I've made the remaining changes. I opted not to use @rhendric's solution for the reasons Harry stated above. I haven't tested this locally, so I'm not sure if any changes merged since this PR was created will cause CI to fail.

**Comment by rhendric** [comment]
You'll want to rebase this to get the changelog entry to appear in the correct section. (Every PR that spans a release needs this; it's the price of maintaining a changelog manually.)

**Comment by JordanMartinez** [comment]
If I rebased, wouldn't the resulting commits drop the credit due `ncaq`? Either way, I've merged `master` into this PR and fixed the changelog.

**Comment by rhendric** [comment]
Merge is fine too. It'll all get squashed in the end, so either way the authors of the final commit will be the authors of all the original commits, and the committer of the final commit will be whoever clicks the button.

**Comment by JordanMartinez** [comment]
This PR is ready for another review.

**Review by rhendric — APPROVED** [review]

**Review by hdgarrood — APPROVED** [review]
