### PR TITLE
Uses strict Map to fix a compile time regression

### LINKED ISSUE #4491: Regression in compilation time and memory in Purescript > 0.15.2
## Description

Regression in compilation time and memory in Purescript 0.15.9 (likely introduced in Purescript 0.15.3 by  https://github.com/purescript/purescript/pull/3915). 

At Lumi, we have a large "Types" which is generated from Haskell datatypes and custom generic code. This file is always the slowest in our compilation chain, however it significantly worsened when we tried upgrading from 0.14.7. The purs compiler RAM usage was most significant, growing to 30GB of ram during the compilation phase. @MonoidMusician recommended I try Purescript 0.15.2, and while there was a small increase from 0.14.7, the RAM was only 2GB during compilation of the large types file.

## To Reproduce

The Types file has 430 newtypes and 250 data type definitions and otherwise contains only instances. A sample newtype definition looks like:

```purescript
newtype Address
  = Address
    { "id" :: Key Address
    , "status" :: LocationStatus
    , "name" :: Maybe String
    , "type_" :: Maybe AddressType
    , "fullName" :: String
    , "company" :: Maybe String
    , "address" :: String
    , "aptSuite" :: Maybe String
    , "city" :: String
    , "country" :: String
    , "state" :: Maybe String
    , "postalCode" :: Maybe String
   }

derive instance genericAddress :: Generic Address _
derive instance newtypeAddress :: Newtype Address _

instance decodeAddress :: Decode Address where
  decode = genericDecode jsonOptions

instance encodeAddress :: Encode Address where
  encode = genericEncode jsonOptions
```
The Encode/Decode instances use purescript-foreign (the working groups port to 15.x). At first I thought maybe this library's approach was introducing a regression but I did a POC to switch to argonaught generics and found similar, if not slightly worse compiler performance.

There are also some polymorphic types such as:
```purescript
newtype ApiResponse a1 a0
  = ApiResponse
    { "warnings" :: Array a1
    , "result" :: a0
    }

derive instance genericApiResponse :: Generic (ApiResponse a1 a0) _
derive instance newtypeApiResponse :: Newtype (ApiResponse a1 a0) _

instance decodeApiResponse :: (Decode a1, Decode a0, DecodeWithOptions a1, DecodeWithOptions a0) => Decode (ApiResponse a1 a0) where
  decode = genericDecode jsonOptions

instance encodeApiResponse :: (Encode a1, Encode a0, EncodeWithOptions a1, EncodeWithOptions a0) => Encode (ApiResponse a1 a0) where
  encode = genericEncode jsonOptions
```

A sample data type is:

```purescript
data ClientUpdate
  = ClientSetAssignedUser
    (Maybe (Key User))
  | ClientReactivate
  | ClientDeactivate
    ClientDeactivation

derive instance genericClientUpdate :: Generic ClientUpdate _

instance decodeClientUpdate :: Decode ClientUpdate where
  decode = genericDecode jsonOptions

instance encodeClientUpdate :: Encode ClientUpdate where
  encode = genericEncode jsonOptions
```

## Expected behavior

The purs compiler takes no more than 2GB during compilation. 

## Additional context

This has been tested so far on a Mac M1. With Purescript 15.9 I was using the arm binaries and for 15.2 the x86 with rosetta emulation. I can also get some statistics on Linux if that would be helpful.

We also attempted generation of non-generic encodings. This definitely had a large impact on compilation memory and time, bringing it down to a more manageable  ~8GB RAM but still elevated more than 15.2.

## PureScript version

0.15.9

### PR DESCRIPTION
**Pull request by mjrussell**
**Description of the change**

For extremely large files (14K lines) with a lot of types and instances memory increases dramatically using Lazy Maps, causing swapping and an big increase in compilation time.

Switching to a strict map brings compilation performance close to 15.2 levels.

Fixes #4491

---

**Checklist:**

- [x] Added a file to CHANGELOG.d for this PR (see CHANGELOG.d/README.md)
- [x] Added myself to CONTRIBUTORS.md (if this is my first contribution)
- [x] Linked any existing issues or proposals that this pull request should close
- [ ] Updated or added relevant documentation
- [ ] Added a test for the contribution (if applicable)

### CODE REVIEW

**Comment by rhendric** [comment]
Would you mind adding an entry for this in CHANGELOG.d? (See CHANGELOG.d/README.md for guidance.)

Otherwise LGTM, assuming the build raises no issues! And thanks for ferreting this out.

**Comment by mjrussell** [comment]
> Would you mind adding an entry for this in CHANGELOG.d? (See CHANGELOG.d/README.md for guidance.)

Done!

**Review by JordanMartinez — APPROVED** [review]

File: src/Language/PureScript/CoreFn/CSE.hs [hunk 1]
```diff
@@ -216,7 +216,7 @@ newScope isTopLevel body = local goDeeper $ do
     if isTopLevel
     then env{ _depth = depth', _deepestTopLevelScope = depth' }
     else env{ _depth = depth' }
-    where 
+    where
```
Comment (JordanMartinez) [inline src/Language/PureScript/CoreFn/CSE.hs:219]: Is this change caused by whitespace? If so, can that be undone?

Comment (mjrussell) [reply src/Language/PureScript/CoreFn/CSE.hs:219]: Yeah there was a trailing whitespace my editor deleted, I can undo that if you want to keep it

Comment (rhendric) [reply src/Language/PureScript/CoreFn/CSE.hs:219]: I say leave it; ordinarily I'd want to keep changes like this from distracting from the diff but this diff is tiny and the change is very unobjectionable.

**Comment by JordanMartinez** [comment]
Looks like the ARM builds are not starting again.

**Comment by f-f** [comment]
Having a look - @JordanMartinez feel free to tag me when this happens

**Comment by f-f** [comment]
They are back up 👍

**Review by f-f — APPROVED** [review]

**Review by rhendric — APPROVED** [review]
