### PR TITLE
Check all recursive paths in data binding groups

### LINKED ISSUE #3918: Recursive binding group check for type synonyms fails to catch some loops in row types
## Description

You can get the compiler to accept some recursive type synonyms as long as one of the synonyms has a branch going through a newtype. Trying to construct one of these values makes the typechecker loop.

## To Reproduce

```purescript
module Loop where

type A = B
type B = { a :: A, b :: Loop }
data Loop = Loop B

boom = Loop {}
```

## Expected behavior

The compiler should reject this since there is a recursive path that does not go through a newtype.

## Additional context

The current check allows recursion as long as there is data/newtype in the group, assuming that this breaks the loop. In the case of this record/row type, one branch is broken through data, but another loops directly. We would need to further reduce the binding group to check that _all_ paths go through data/newtype.

## PureScript version

0.13.8 and master

### PR DESCRIPTION
**Pull request by natefaubion**
This changes the data binding group check to follow all dependency paths, looking for loops in synonyms.

Fixes #3918

### CODE REVIEW

**Review by garyb — APPROVED** [review]

**Comment by kl0tl** [comment]
This also fixes https://github.com/purescript/purescript/issues/3735!

File: src/Language/PureScript/Sugar/BindingGroups.hs [hunk 1]
```diff
@@ -224,21 +225,36 @@ toBindingGroup moduleName (CyclicSCC ds') = do
...
   where
   kindDecl (KindDeclaration sa _ pn _) = [(fst sa, Qualified Nothing pn)]
   kindDecl (ExternDataDeclaration sa pn _) = [(fst sa, Qualified Nothing pn)]
   kindDecl _ = []
 
+  getDecl (decl, _, _) = decl
+  getName (_, name, _) = name
+  lookupVert name = find ((==) name . getName) ds'
+
+  depsTerminate seen _ [] = Just seen
```
Comment (hdgarrood) [inline src/Language/PureScript/Sugar/BindingGroups.hs:247]: I think this function could do with some documentation. Would this be accurate?

> This function ensures that all paths through an SCC which start and end at a given type synonym involve at least one vertex which is not a type synonym. This is necessary to prevent loops while expanding type synonyms.
> In this function:
> - `seen` is the list of names we know are safe, either because they are not type synonyms, or because we have already checked that all paths through the SCC starting and ending at that vertex involve one non-type-synonym vertex
> - `stop` is the current path of unbroken type synonym vertices being checked for cycles
>
> This function either returns Nothing in the case that a type synonym cycle was found, or Just a list of seen names in the case where no cycles were found.

Also, could we have it return a `Left stop` if we did find a cycle, and then use `stop` in the error message, in the same way that the other CycleInX error constructors take a list of names involved in the cycle?

Comment (natefaubion) [reply src/Language/PureScript/Sugar/BindingGroups.hs]: I've changed the implementation to use SCC to find all cycles in group, and I've changed the error to include all the names in the cycles.

File: tests/purs/failing/InfiniteKind2.out [hunk 2]
```diff
@@ -10,7 +10,7 @@ at tests/purs/failing/InfiniteKind2.purs:5:23 - 5:27 (line 5, column 23 - line 5
 while checking that type [33mTree[0m
   has kind [33mt0[0m
 while inferring the kind of [33mm Tree[0m
-in type constructor [33mTree[0m
+in data binding group Tree
```
Comment (natefaubion) [inline tests/purs/failing/InfiniteKind2.out:13]: I'm not sure what this change is about.

Comment (natefaubion) [reply tests/purs/failing/InfiniteKind2.out:13]: Oh I see. I took out the singleton synonym check. I think this is actually correct now since it is a cyclical type.

**Review by hdgarrood — APPROVED** [review]
Nice! I like the new stronglyConnCompR implementation, that’s very easy to follow.
