### PR TITLE
[purs repl] Allows to :browse Prim.* modules

### LINKED ISSUE #3362: :browse Prim.Row doesn't work in master
`Prim` works but the other `Prim` modules don't.

### PR DESCRIPTION
**Pull request by kRITZCREEK**
Fixes #3362

### CODE REVIEW

File: src/Language/PureScript/Constants.hs [hunk 1]
```diff
@@ -448,6 +448,9 @@ pattern Fail = Qualified (Just PrimTypeError) (ProperName "Fail")
 pattern Warn :: Qualified (ProperName 'ClassName)
 pattern Warn = Qualified (Just PrimTypeError) (ProperName "Warn")
 
+primModules :: [ModuleName]
+primModules = [Prim, PrimOrdering, PrimRow, PrimRowList, PrimSymbol, PrimTypeError]
```
Comment (garyb) [inline src/Language/PureScript/Constants.hs]: Much better 👍

**Comment by kRITZCREEK** [comment]
Thanks :)
