### PR TITLE
Treat type annotations on top-level expressions as if they were type declarations

### LINKED ISSUE #2362: Compiler infers wrong constraints for inline annotations
In `psci`:

```purescript
import Prelude
f = (\x -> show (x + x)) :: forall a. a -> String
```
compiles just fine and infers the following type for `f`:
```
(Show a0, Semiring a0) => (forall a. a -> String)
```

However with a standalone type declaration like so:
```purescript
import Prelude
f  :: forall a. a -> String
f = (\x -> show (x + x))
```

`psc` correctly fails with:

```
 No type class instance was found for

    Data.Show.Show a0
```

### PR DESCRIPTION
**Pull request by paf31**
Treat type annotations on top-level expressions as if they were type declarations.

### CODE REVIEW

File: src/Language/PureScript/TypeChecker/Types.hs [hunk 1]
```diff
@@ -199,6 +201,10 @@ typeForBindingGroupElement (ident, val) dict untypedDict = do
 -- | Check if a value contains a type annotation
 isTyped :: (Ident, Expr) -> Either (Ident, Expr) (Ident, (Expr, Type, Bool))
 isTyped (name, TypedValue checkType value ty) = Right (name, (value, ty, checkType))
+isTyped (name, PositionedValue pos c value) =
+  bimap (second (PositionedValue pos c))
+        (second (\(e, t, b) -> (PositionedValue pos c e, t, b)))
+        (isTyped (name, value))
```
Comment (kRITZCREEK) [inline src/Language/PureScript/TypeChecker/Types.hs]: Does this mean `PositionedValue` can only appear at the top level? Or does isTyped only get called on values that are at the top level?

**Comment by kRITZCREEK** [comment]
Looks good to me! Just the one question to make sure I understood things right.

File: src/Language/PureScript/TypeChecker/Types.hs (hunk 1 above)
Comment (paf31) [inline src/Language/PureScript/TypeChecker/Types.hs]: At the top level, there are `TypedValue`s under `PositionedValue`, but those should be the only two constructors we need to remove to find a type annotation.
