### PR TITLE
Fix the duplicate/redefined module error

### LINKED ISSUE #1828: DuplicateModuleName error does not specify what file Modules are defined in
I split up my file into multiple files and missed a `module Parser where` somewhere so I get

     Module Parser has been defined multiple times.

It would be good if this said what files the modules are defined in.

I had a quick look and `RedefinedModule` does seem to specify filenames but `DuplicateModuleName` does not. I don't know why my example triggers the latter (using `pulp build`) and I can't see a way to get at filenames where `DuplicateModule` is called.

Happy to have another look at fixing this with some guidance.

### PR DESCRIPTION
**Pull request by garyb**
Resolves #1828

### CODE REVIEW

File: src/Language/PureScript/Sugar/Names.hs [hunk 1]
```diff
@@ -99,15 +99,12 @@ desugarImportsWithEnv externs modules = do
     exportedRefs f = M.fromList $ (, efModuleName) <$> mapMaybe f efExports
 
   updateEnv :: ([Module], Env) -> Module -> m ([Module], Env)
-  updateEnv (ms, env) m@(Module ss _ mn _ refs) =
-    case mn `M.lookup` env of
-      Just m' -> throwError . errorMessage $ RedefinedModule mn [envModuleSourceSpan m', ss]
```
Comment (garyb) [inline src/Language/PureScript/Sugar/Names.hs]: No need to check if a module already exists in the name environment anymore since it will be caught during `Make` and the error raised there.

**Comment by garyb** [comment]
Any ideas on why that test would fail on some platforms/configs? 😕

**Comment by garyb** [comment]
Hmm, weird, still failing.

**Comment by garyb** [comment]
Ok, we're good now, it was due to missing files in the cabal file. The coverage build is failing due to a dependency issue though... the same is true of `master`.

**Comment by paf31** [comment]
👍
