### PR TITLE
Fix backtick offside rule

### LINKED ISSUE #4171: Infix names with backticks don't use the same offside rule as operators
## Description

Infix (backtick) names do not affect layout in the same way as operators do. Operators use the `offsideEndP` rule which lets you write:

```purescript
example = do
  foo bar
  <|> baz
```

An operator at the same column as a layout block will close the layout block. Infix expressions use the `offsideP` rule through `insertDefault`.

```purescript
example = do
  foo bar
  `wat` baz
```

This will result in a parse error. It should parse with the same offside rule as operators.

## Additional context

https://github.com/natefaubion/purescript-tidy/issues/15#issuecomment-894552462

## PureScript version

0.14.3

### PR DESCRIPTION
**Pull request by JordanMartinez**
**Description of the change**

Fixes #4171 by applying the change suggested by Nate in that issue. 

I'm guessing this is not entirely correct because one of the other golden tests was affected by this change, too.

---

**Checklist:**

- [x] Added a file to CHANGELOG.d for this PR (see CHANGELOG.d/README.md)
- [x] Linked any existing issues or proposals that this pull request should close
- [ ] Updated or added relevant documentation
- [x] Added a test for the contribution (if applicable)

### CODE REVIEW

File: lib/purescript-cst/src/Language/PureScript/CST/Layout.hs [hunk 1]
```diff
@@ -265,7 +265,7 @@ insertLayout src@(SourceToken tokAnn tok) nextPos stack =
         ((_, LytTick) : stk', acc') ->
           (stk', acc') & insertToken src
         _ ->
-          state & insertDefault & pushStack tokPos LytTick
+          state & collapse offsideEndP & insertSep & insertToken src
```
Comment (natefaubion) [inline lib/purescript-cst/src/Language/PureScript/CST/Layout.hs:268]: You still need to `pushStack`. We should only be replaced the `insertDefault`.

Comment (JordanMartinez) [reply lib/purescript-cst/src/Language/PureScript/CST/Layout.hs]: Ah... Now I see.

**Comment by JordanMartinez** [comment]
I tried testing this locally and it seemed to just hang. Not sure how CI will do, but I pushed my changes anyways.

File: tests/purs/layout/BacktickOperator.purs [hunk 2]
```diff
@@ -0,0 +1,16 @@
...
+
+example2 = do
+  foo bar
+  `wat` baz
+
+example3 =
+  case _ of
+    Foo a -> 1
+    Bar b -> 2
+  `append` 3
```
Comment (natefaubion) [inline tests/purs/layout/BacktickOperator.purs:15]: I think this should be indented to the same level as the case branches, not the case keyword.

Comment (JordanMartinez) [reply tests/purs/layout/BacktickOperator.purs]: Ah... Done.

**Review by natefaubion — APPROVED** [review]

File: tests/purs/layout/BacktickOperator.out [hunk 3]
```diff
@@ -0,0 +1,16 @@
...
+
+example2 = do{
+  foo bar}
+  `wat` baz;
+
+example3 =
+  case _ of{
+    Foo a -> 1;
+    Bar b -> 2}
+    `append` 3}
```
Comment (rhendric) [inline tests/purs/layout/BacktickOperator.out:15]: This isn't right, is it? First, the braces don't match; second, I'd expect
```suggestion
  {case _ of
    Foo a -> 1;
    Bar b -> 2}
    `append` 3
```

(which of course wouldn't type check, because `append` would need type `(a -> Int) -> Int -> b`, but that's not really relevant to a layout test).

Compare with how
```purs
example3 =
  case _ of
    Foo a -> 1
    Bar b -> 2
    + 3
```
currently parses.

Comment (natefaubion) [reply tests/purs/layout/BacktickOperator.out:15]: That last `}` is the layout end of the module, I think.

Comment (natefaubion) [reply tests/purs/layout/BacktickOperator.out:15]: I agree we should have a comparable test here for case with operators, since there is one for `do`.

Comment (rhendric) [reply tests/purs/layout/BacktickOperator.out:15]: :facepalm: Of course it is. Okay, guess this all makes sense after all!

Comment (JordanMartinez) [reply tests/purs/layout/BacktickOperator.out]: I've added a case for operators.

**Comment by JordanMartinez** [comment]
Do I need to add more content to the changelog entry? The description by itself doesn't really explain what this does, but I also don't think this needs to be explained as anyone who wants to know could just look at the diff here.
